//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    
    public class CreationResult<T>
        where T :  class
    {
        
        public Boolean Ok { get; private set; }
        
        public List<DomainEventBase> DomainEvents { get; private set; }
        
        public List<string> DomainErrors { get; private set; }
        
        public T CreatedEntity { get; private set; }
        
        private CreationResult(Boolean Ok, List<DomainEventBase> DomainEvents, List<string> DomainErrors, T CreatedEntity)
        {
            this.Ok = Ok;
            this.DomainEvents = DomainEvents;
            this.DomainErrors = DomainErrors;
            this.CreatedEntity = CreatedEntity;
        }
        
        public static CreationResult<T> OkResult(List<DomainEventBase> DomainEvents, T CreatedEntity)
        {
            return new CreationResult<T>(true, DomainEvents, new List<string>(), CreatedEntity);
        }
        
        public static CreationResult<T> ErrorResult(List<string> DomainErrors)
        {
            return new CreationResult<T>(false, new List<DomainEventBase>(), DomainErrors, null);
        }
    }
}
