//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    
    
    public interface IUser
    {
        
        GenericWebServiceBuilder.UserCreateEvent Create(string Name);
    }
    
    public partial class User : IUser
    {
        
        private string _Name;
        
        public string Name
        {
            get
            {
                return this._Name;
            }
        }
    }
}
