//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsyncHost
{
    using System;
    using Application;
    using Microsoft.Extensions.DependencyInjection;
    using Hangfire;
    using Microsoft.AspNetCore.Builder;
    using SqlAdapter;
    using Application.Users;
    using SqlAdapter.Users;
    using Application.Posts;
    using SqlAdapter.Posts;
    using Application.Users.AsyncHooks;
    
    
    public class GeneratedDependencies
    {
        
        public static void ConfigureGeneratedServices(IServiceCollection collection)
        {
            collection.AddTransient<IEventStore, EventStore>();
            collection.AddTransient<IEventStoreRepository, EventStoreRepository>();
            collection.AddTransient<IQueueRepository, QueueRepository>();
            collection.AddTransient<EventJobRegistration>();
            collection.AddTransient<IHangfireQueue, HangfireQueue>();
            collection.AddTransient<IUserRepository, UserRepository>();
            collection.AddTransient<IPostRepository, PostRepository>();
            collection.AddTransient<OnUserCreateSendWelcomeMailEventHandler>();
            collection.AddTransient<OnUserCreateSendWelcomeMailAsyncHook>();
            collection.AddTransient<OnUserCreateSendPasswordMailEventHandler>();
            collection.AddTransient<OnUserCreateSendPasswordMailAsyncHook>();
            collection.AddTransient<OnUserUpdateAgeSendBirthdayMailEventHandler>();
            collection.AddTransient<OnUserUpdateAgeSendBirthdayMailAsyncHook>();
        }
        
        public static void ConfigureApplication(IApplicationBuilder app)
        {
            var option = new BackgroundJobServerOptions {WorkerCount = 1};
            app.UseHangfireServer(option);
            app.UseHangfireDashboard();
            RecurringJob.AddOrUpdate<OnUserCreateSendWelcomeMailEventHandler>(handler => handler.Run(), Cron.Minutely());
            RecurringJob.AddOrUpdate<OnUserCreateSendPasswordMailEventHandler>(handler => handler.Run(), Cron.Minutely());
            RecurringJob.AddOrUpdate<OnUserUpdateAgeSendBirthdayMailEventHandler>(handler => handler.Run(), Cron.Minutely());
        }
    }
}
