//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Users.AsyncHooks
{
    using System;
    using Application;
    using System.Threading.Tasks;
    using System.Collections.Generic;
    using Domain.Users;
    
    
    public class OnUserUpdateAgeSendBirthdayMailEventHandler
    {
        
        public OnUserUpdateAgeSendBirthdayMailAsyncHook AsyncHook { get; private set; }
        
        public IHangfireQueue HangfireQueue { get; private set; }
        
        public OnUserUpdateAgeSendBirthdayMailEventHandler(OnUserUpdateAgeSendBirthdayMailAsyncHook AsyncHook, IHangfireQueue HangfireQueue)
        {
            this.AsyncHook = AsyncHook;
            this.HangfireQueue = HangfireQueue;
        }
        
        public async Task Run()
        {
            var events = await HangfireQueue.GetEvents("SendBirthdayMail");
            var handledEvents = new List<EventAndJob>();
            var enumerator = events.GetEnumerator();
            for (
            ; enumerator.MoveNext(); 
            )
            {
                var eventWrapper = enumerator.Current;
                var domainEvent = (UserUpdateAgeEvent) eventWrapper.DomainEvent;
                var hookResult = await AsyncHook.Execute(domainEvent);
                if (hookResult.Ok)
                {
                    handledEvents.Add(eventWrapper);
                }
            }
            await HangfireQueue.RemoveEventsFromQueue(handledEvents);
        }
    }
}
