//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlAdapter
{
    using System;
    using System.Collections.Generic;
    using Domain.Users;
    
    
    public class EventJobRegistration
    {
        
        public List<EventTuple> EventJobs { get; private set; }
        
        public EventJobRegistration()
        {
            EventJobs = new List<EventTuple>();
            EventJobs.Add(new EventTuple(typeof(UserCreateEvent).ToString(), "SendWelcomeMail"));
            EventJobs.Add(new EventTuple(typeof(UserCreateEvent).ToString(), "SendPasswordMail"));
            EventJobs.Add(new EventTuple(typeof(UserUpdateAgeEvent).ToString(), "SendBirthdayMail"));
        }
    }
}
