//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlAdapter
{
    using System;
    using Application;
    using System.Threading.Tasks;
    using Domain;
    using System.Collections.Generic;
    using System.Linq;
    using Microsoft.EntityFrameworkCore;
    
    
    public class QueueRepository : IQueueRepository
    {
        
        public HangfireContext Context { get; private set; }
        
        public QueueRepository(HangfireContext Context)
        {
            this.Context = Context;
        }
        
        public async Task AddEventForJob(EventAndJob eventAndJob)
        {
            Context.EventAndJobQueue.Add(eventAndJob);
            await Context.SaveChangesAsync();
        }
        
        public async Task<List<EventAndJob>> GetEvents( string jobName)
        {
            var eventList = await Context.EventAndJobQueue.Include(queue => queue.DomainEvent).Where(eve => eve.JobName == jobName).ToListAsync();
            return eventList;
        }
        
        public async Task RemoveEventsFromQueue(List<EventAndJob> handledEvents)
        {
            Context.EventAndJobQueue.RemoveRange(handledEvents);
            await Context.SaveChangesAsync();
        }
    }
}
