//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application
{
    using System;
    using Domain;
    
    
    public class EventAndJob
    {
        
        public Guid Id { get; private set; }
        
        public DomainEventBase DomainEvent { get; private set; }
        
        public  string JobName { get; private set; }
        
        public EventAndJob(DomainEventBase DomainEvent,  string JobName)
        {
            this.DomainEvent = DomainEvent;
            this.JobName = JobName;
            this.Id = Guid.NewGuid();
        }
        
        private EventAndJob()
        {
        }
    }
}
