//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application
{
    using System;
    using Domain;
    using System.Threading.Tasks;
    
    
    public interface IDomainHook
    {
        
        Type EventType
        {
            get;
        }
        
        Task<HookResult> ExecuteSavely(DomainEventBase domainEvent);
    }
}
