//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Users
{
    using System;
    using System.Collections.Generic;
    using Domain.Posts;
    
    
    public class UserAddPostCommand
    {
        
        public Post NewPost { get; private set; }
        
        public Post PostToDelete { get; private set; }
        
        public UserAddPostCommand(Post NewPost, Post PostToDelete)
        {
            this.NewPost = NewPost;
            this.PostToDelete = PostToDelete;
        }
    }
}
