//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Users
{
    using System;
    using System.Collections.Generic;
    using Domain.Posts;
    
    
    public class UserAddPinnedPostCommand
    {
        
        public Post NewPost { get; private set; }
        
        public UserAddPinnedPostCommand(Post NewPost)
        {
            this.NewPost = NewPost;
        }
    }
}
