//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Users
{
    using System;
    
    
    public class UserAddPinnedPostEvent : DomainEventBase
    {
        
        public Guid PostId { get; private set; }
        
        private UserAddPinnedPostEvent() : 
                base(Guid.Empty)
        {
        }
        
        public UserAddPinnedPostEvent(Guid PostId, Guid EntityId) : 
                base(EntityId)
        {
            this.PostId = PostId;
        }
    }
}
