//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Users
{
    using System;
    using System.Collections.Generic;
    using Domain.Posts;
    
    
    public partial class User : UserBase
    {
        
        public List<Post> MyPosts { get; private set; } = new List<Post>();
        
        public String Name { get; private set; }
        
        public Int32 Age { get; private set; }
        
        public Post PinnedPost { get; private set; }
        
        public Guid Id { get; private set; }
        
        private User(Guid Id, UserCreateCommand command)
        {
            this.Name = command.Name;
            this.Age = command.Age;
            this.Id = Id;
        }
        
        private User()
        {
        }
    }
    
    public abstract class UserBase
    {
        
        public abstract ValidationResult UpdateAge(UserUpdateAgeCommand command);
        
        public abstract ValidationResult UpdateName(UserUpdateNameCommand command);
        
        public abstract ValidationResult AddPost(UserAddPostCommand command);
        
        public abstract ValidationResult CheckAgeRequirement_OnMyPostsUpdateTitle(PostUpdateTitleEvent hookEvent);
        
        public abstract ValidationResult CheckAgeRequirement_OnPinnedPostUpdateTitle(PostUpdateTitleEvent hookEvent);
    }
}
