//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HttpAdapter.Users
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Domain.Users;
    using Microsoft.AspNetCore.Mvc;
    using Application.Users;
    
    
    [Route("api/users")]
    public class UserController : Controller
    {
        
        public UserCommandHandler Handler { get; private set; }
        
        public UserController(UserCommandHandler Handler)
        {
            this.Handler = Handler;
        }
        
        [HttpPost()]
        public async Task<IActionResult> CreateUser([FromBody] UserCreateCommand command)
        {
            return await Handler.CreateUser(command);
        }
        
        [HttpPut("{id}/updateage")]
        public async Task<IActionResult> UpdateAge(Guid id, [FromBody] UserUpdateAgeCommand command)
        {
            return await Handler.UpdateAgeUser(id, command);
        }
        
        [HttpPut("{id}/updatename")]
        public async Task<IActionResult> UpdateName(Guid id, [FromBody] UserUpdateNameCommand command)
        {
            return await Handler.UpdateNameUser(id, command);
        }
        
        [HttpPut("{id}/addpost")]
        public async Task<IActionResult> AddPost(Guid id, [FromBody] UserAddPostApiCommand command)
        {
            return await Handler.AddPostUser(id, command);
        }
        
        [HttpPut("{id}/addpinnedpost")]
        public async Task<IActionResult> AddPinnedPost(Guid id, [FromBody] UserAddPinnedPostApiCommand command)
        {
            return await Handler.AddPinnedPostUser(id, command);
        }
        
        [HttpGet("{id}")]
        public async Task<IActionResult> GetUser(Guid id)
        {
            return await Handler.GetUser(id);
        }
        
        [HttpGet()]
        public async Task<IActionResult> GetUsers()
        {
            return await Handler.GetUsers();
        }
    }
}
