//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Users
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Domain.Users;
    
    
    public interface IUserRepository
    {
        
        Task CreateUser(User user);
        
        Task UpdateUser(User user);
        
        Task<User> GetUser(Guid id);
        
        Task<List<User>> GetUsers();
        
        Task<User> GetMyPostsParent(Guid childId);
        
        Task<User> GetPinnedPostParent(Guid childId);
    }
}
