//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Posts
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Domain.Posts;
    
    
    public interface IPostRepository
    {
        
        Task CreatePost(Post post);
        
        Task UpdatePost(Post post);
        
        Task<Post> GetPost(Guid id);
        
        Task<List<Post>> GetPosts();
    }
}
